### PR TITLE
Added a fix for the issue https://issuetracker.google.com/issues/227926002.

### PR DESCRIPTION
**Pull request by binishmatheww**
Navigation Compose does not show startDestination on Xiaomi device. 
Device : Poco X3 pro.
Android version : 12

### CODE REVIEW

**Comment by racka98** [comment]
This is a really interesting bug. This is Android 12 only? I have a Xiaomi Redmi 10C that I use for testing sometimes thats on A11 without this issue.

**Comment by racka98** [comment]
Though I'll hold of merging this since I've doing some migrations in the `kotlinx-immutable-compose` branch: https://github.com/ReluctApp/Reluct/tree/kotlinx-immutable-compose. That's why you saw the name arguments for the charts where missing. I'll merge the changes I made first then I'll take a look

**Comment by binishmatheww** [comment]
I'm not sure if this is Android 12+ only. I encountered this bug when I started using compose navigation. When I installed Reluct app, I faced this issue. start destination won't be loaded until you touch the screen.

**Comment by binishmatheww** [comment]
Check this out for more info : https://issuetracker.google.com/issues/227926002

**Pull request closed without merging**
