### PR TITLE
Added a fix for the issue https://issuetracker.google.com/issues/227926002.

### PR DESCRIPTION
**Pull request by binishmatheww**
Navigation Compose does not show startDestination on Xiaomi devices until the user touches the screen.
Device : Poco X3 pro.
Android version : 12.

### CODE REVIEW

**Comment by racka98** [comment]
Have you tried setting the background of the Activity to transparent? In themes.xml.

**Comment by racka98** [comment]
Also is there a way to detect if its a Xiaomi device and only apply a fix to those? Not so sure about imposing this "hack" onto every device.

**Comment by binishmatheww** [comment]
Yes. I have tried setting the background to transparent. Actually, background being transparent is not the fix here. Changing the background to transparent from the default background triggers something. Hence, it loads the startDestination.
Also, you can check if a device is made by xiaomi or not by checking the Build.MANUFACTURER value.
like this : `Build.MANUFACTURER.equals(other = "xiaomi", ignoreCase = true)`

**Comment by racka98** [comment]
Can you please add that check, make your fix a function then call it in the activity. The function can be defined below inside the Activity and should be private.

Merging this after that little fix so I can release a new version tomorrow

**Comment by binishmatheww** [comment]
I have added the functions. Could you please verify and merge it ?
Thanks and all the best.

**Comment by racka98** [comment]
Looks good 👍

**Pull request merged**
